// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
import CoreGraphics
import MapConductorIcons

/// Map symbols from the jp pack. Selection is always explicit.
public enum JapanMapIcons {
    /// Japanese post office.
    public static let postOffice = MapIconGlyph(
        id: "jp.post_office",
        commands: [
            .moveTo(CGPoint(x: 4, y: 4)),
            .lineTo(CGPoint(x: 20, y: 4)),
            .lineTo(CGPoint(x: 20, y: 7)),
            .lineTo(CGPoint(x: 4, y: 7)),
            .close,
            .moveTo(CGPoint(x: 6, y: 9)),
            .lineTo(CGPoint(x: 18, y: 9)),
            .lineTo(CGPoint(x: 18, y: 12)),
            .lineTo(CGPoint(x: 14, y: 12)),
            .lineTo(CGPoint(x: 14, y: 21)),
            .lineTo(CGPoint(x: 10, y: 21)),
            .lineTo(CGPoint(x: 10, y: 12)),
            .lineTo(CGPoint(x: 6, y: 12)),
            .close,
        ]
    )

    /// Japanese police box or koban.
    public static let policeBox = MapIconGlyph(
        id: "jp.police_box",
        commands: [
            .moveTo(CGPoint(x: 10, y: 2)),
            .lineTo(CGPoint(x: 14, y: 2)),
            .lineTo(CGPoint(x: 15, y: 6)),
            .lineTo(CGPoint(x: 20, y: 9)),
            .lineTo(CGPoint(x: 18, y: 11)),
            .lineTo(CGPoint(x: 18, y: 21)),
            .lineTo(CGPoint(x: 6, y: 21)),
            .lineTo(CGPoint(x: 6, y: 11)),
            .lineTo(CGPoint(x: 4, y: 9)),
            .lineTo(CGPoint(x: 9, y: 6)),
            .close,
            .moveTo(CGPoint(x: 9, y: 12)),
            .lineTo(CGPoint(x: 15, y: 12)),
            .lineTo(CGPoint(x: 15, y: 16)),
            .lineTo(CGPoint(x: 9, y: 16)),
            .close,
        ]
    )

    /// Shinto shrine.
    public static let shrine = MapIconGlyph(
        id: "jp.shrine",
        commands: [
            .moveTo(CGPoint(x: 3, y: 3)),
            .lineTo(CGPoint(x: 21, y: 3)),
            .lineTo(CGPoint(x: 21, y: 6)),
            .lineTo(CGPoint(x: 3, y: 6)),
            .close,
            .moveTo(CGPoint(x: 5, y: 8)),
            .lineTo(CGPoint(x: 19, y: 8)),
            .lineTo(CGPoint(x: 19, y: 11)),
            .lineTo(CGPoint(x: 5, y: 11)),
            .close,
            .moveTo(CGPoint(x: 7, y: 6)),
            .lineTo(CGPoint(x: 10, y: 6)),
            .lineTo(CGPoint(x: 9, y: 21)),
            .lineTo(CGPoint(x: 6, y: 21)),
            .close,
            .moveTo(CGPoint(x: 14, y: 6)),
            .lineTo(CGPoint(x: 17, y: 6)),
            .lineTo(CGPoint(x: 18, y: 21)),
            .lineTo(CGPoint(x: 15, y: 21)),
            .close,
        ]
    )
}
